---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-view-highpon-com-v1-scratchexternalsecret
  failurePolicy: Fail
  name: mscratchexternalsecret.kb.io
  rules:
  - apiGroups:
    - view.highpon.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scratchexternalsecrets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-view-highpon-com-v1-scratchexternalsecret
  failurePolicy: Fail
  name: vscratchexternalsecret.kb.io
  rules:
  - apiGroups:
    - view.highpon.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scratchexternalsecrets
  sideEffects: None
