---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - view.highpon.com
  resources:
  - scratchexternalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.highpon.com
  resources:
  - scratchexternalsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - view.highpon.com
  resources:
  - scratchexternalsecrets/status
  verbs:
  - get
  - patch
  - update
