# permissions for end users to edit scratchexternalsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: scratchexternalsecret
    app.kubernetes.io/managed-by: kustomize
  name: scratchexternalsecret-editor-role
rules:
- apiGroups:
  - view.highpon.com
  resources:
  - scratchexternalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.highpon.com
  resources:
  - scratchexternalsecrets/status
  verbs:
  - get
